name: agentic-hackathon
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - google-generativeai
      - jupyter
      - numpy
      - pandas
      - requests
      - flask
      - matplotlib
      - openai 